apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: amF2YWltYWdl   # base64 encoded value of 'postgres'
  postgres-password: dGVzdDEyMw==      # base64 encoded value of 'secret'
  postgres-dbname: ZnVsbHN0YWNramF2YQ==     # base64 encoded value of 'database'
