apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: akshay
        image: akshay4444/imagestore:springhardcorepassnew@sha256:01f75f94a6ae85b6b341d180713dc3f85b2961859393487da2c2280750202673
        ports:
        - containerPort: 8080