apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  labels:
    run: spring
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
   # nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app:  spring
